In [2]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [3]:
import torch
from torch import nn, Tensor
from torch.nn import functional as F

In [4]:
y = Tensor([3]).long()

In [5]:
y_pred_far = F.log_softmax(Tensor([[5,3,1,0,1,3,5]]), -1)

In [6]:
y_pred_good = F.log_softmax(Tensor([[0,0,0,10,0,0,0]]), -1)

In [7]:
y_pred_close = F.log_softmax(Tensor([[1,3,5,10,5,3,1]]), -1)

In [8]:
y_pred_offset = F.log_softmax(Tensor([[1,3,10,5,5,3,1]]), -1)

In [9]:
y_pred_offset2 = F.log_softmax(Tensor([[10,3,1,5,5,3,1]]), -1)

In [10]:
y_pred_good

tensor([[-1.0000e+01, -1.0000e+01, -1.0000e+01, -2.7248e-04, -1.0000e+01,
         -1.0000e+01, -1.0000e+01]])

In [11]:
y_pred_far

tensor([[-0.8390, -2.8390, -4.8390, -5.8390, -4.8390, -2.8390, -0.8390]])

In [12]:
y_pred_close

tensor([[-9.0154, -7.0154, -5.0154, -0.0154, -5.0154, -7.0154, -9.0154]])

In [13]:
F.nll_loss(y_pred_good, y)

tensor(0.0003)

In [14]:
F.nll_loss(y_pred_close, y)

tensor(0.0154)

In [15]:
F.nll_loss(y_pred_far, y)

tensor(5.8390)

In [16]:
F.nll_loss(y_pred_offset, y)

tensor(5.0154)

In [17]:
F.nll_loss(y_pred_offset2, y)

tensor(5.0154)

## Gauss target

# Frac MSE

In [35]:
ints = torch.arange(y_pred_offset2.size(1)); ints

tensor([0, 1, 2, 3, 4, 5, 6])

In [34]:
mses = (y-ints)**2; mses

tensor([9, 4, 1, 0, 1, 4, 9])

In [33]:
losses = mses*torch.exp(y_pred_offset2); losses

tensor([[8.8622e+00, 3.5917e-03, 1.2152e-04, 0.0000e+00, 6.6348e-03, 3.5917e-03,
         1.0937e-03]])

In [36]:
losses.sum(-1)

tensor([8.8773])

In [45]:
def frac_mse(probs, targs):
    ints = torch.arange(probs.size(1))
    mses = (targs-ints)**2
    losses = mses*torch.exp(probs)
    return losses.sum(-1)

In [46]:
frac_mse(y_pred_good, y)

tensor([9, 4, 1, 0, 1, 4, 9])
tensor([[4.0849e-04, 1.8155e-04, 4.5388e-05, 0.0000e+00, 4.5388e-05, 1.8155e-04,
         4.0849e-04]])


tensor([0.0013])

In [47]:
frac_mse(y_pred_far, y)

tensor([9, 4, 1, 0, 1, 4, 9])
tensor([[3.8893, 0.2339, 0.0079, 0.0000, 0.0079, 0.2339, 3.8893]])


tensor([8.2623])

In [48]:
frac_mse(y_pred_close, y)

tensor([9, 4, 1, 0, 1, 4, 9])
tensor([[0.0011, 0.0036, 0.0066, 0.0000, 0.0066, 0.0036, 0.0011]])


tensor([0.0226])

In [49]:
frac_mse(y_pred_offset, y)

tensor([9, 4, 1, 0, 1, 4, 9])
tensor([[0.0011, 0.0036, 0.9847, 0.0000, 0.0066, 0.0036, 0.0011]])


tensor([1.0007])

In [50]:
frac_mse(y_pred_offset2, y)

tensor([9, 4, 1, 0, 1, 4, 9])
tensor([[8.8622e+00, 3.5917e-03, 1.2152e-04, 0.0000e+00, 6.6348e-03, 3.5917e-03,
         1.0937e-03]])


tensor([8.8773])